const applause = new Audio();
const boo = new Audio();
const gasp = new Audio();
const tada = new Audio();
const victory = new Audio();
const wrong = new Audio();
applause.src = "sounds/sound-board_sounds_applause.mp3";
boo.src = "sounds/sound-board_sounds_boo.mp3"
gasp.src = "sounds/sound-board_sounds_gasp.mp3"
tada.src = "sounds/sound-board_sounds_tada.mp3"
victory.src = "sounds/sound-board_sounds_victory.mp3"
wrong.src = "sounds/sound-board_sounds_wrong.mp3"